import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";

const cwd = process.cwd();

function read(relPath: string) {
  return readFileSync(resolve(cwd, relPath), "utf8");
}

describe("Unity embedded session view", () => {
  it("routes the Unity overlay to the shared chat workspace", () => {
    const app = read("src/App.vue");
    const view = read("src/components/UnityEmbeddedSessionView.vue");
    const workspace = read("src/components/ChatWorkspaceView.vue");
    const command = read("src-tauri/src/commands/unity_embed.rs");
    const runtime = read("src/services/locusRuntime.ts");

    expect(command).toContain(String.raw`const CONTROL_PIPE_NAME_PREFIX: &str = r"\\.\pipe\locus_tauri_unity_embed_";`);
    expect(command).toContain('const EMBED_URL: &str = "/unity-embed?host=tauri-overlay";');
    expect(app).toContain("const UnityEmbeddedSessionView = defineAsyncComponent");
    expect(app).toContain("isUnityEmbedWindow");
    expect(app).toContain("<UnityEmbeddedSessionView");
    expect(app).toContain("await bootstrapCritical();");
    expect(app).toContain("await registerListeners();");
    expect(view).toContain("<ChatWorkspaceView");
    expect(view).toContain("activateUnityEmbedForInput");
    expect(view).toContain("setUnityEmbedMouseActivationSuppressed");
    expect(view).toContain("getUnityEmbedFocusDebugSnapshot");
    expect(view).toContain("@pointerdown.capture=\"handlePointerDown\"");
    expect(view).not.toContain("@pointerover.capture");
    expect(view).not.toContain("@pointermove.capture");
    expect(view).toContain("layout-mode=\"auto\"");
    expect(view).not.toContain("default-session-panel-collapsed");
    expect(view).toContain('session-panel-storage-scope="unity"');
    expect(view).toContain("box-shadow: inset 0 1px 0 color-mix(in srgb, var(--border-color) 82%, var(--text-secondary) 18%);");
    expect(workspace).toContain("<ChatView");
    expect(workspace).toContain(':default-session-panel-collapsed="defaultSessionPanelCollapsed"');
    expect(workspace).toContain(':session-panel-storage-scope="sessionPanelStorageScope"');
    expect(workspace).toContain("defaultSessionPanelCollapsed: false");
    expect(workspace).toContain("<ChatView");
    expect(workspace).not.toContain("<ThinkingPanel");
    expect(workspace).toContain("chatStore.showThinkingPanel");
    expect(workspace).not.toContain("chat-session-stack");
    const chatView = read("src/components/ChatView.vue");
    const sidebar = read("src/components/ChatSidebarPanel.vue");
    expect(chatView).toContain("session-sidebar-stack");
    expect(chatView).not.toContain("<ThinkingPanel");
    expect(sidebar).toContain("<ThinkingPanel");
    expect(sidebar).toContain("chat-sidebar-section-thinking");
    expect(workspace).toContain("<ChatSidebarPanel");
    expect(workspace).toContain(':storage-scope="sessionPanelStorageScope"');
    expect(workspace).toContain("@layout-mode-change=\"handleLayoutModeChange\"");
    expect(view).not.toContain("useEmbeddedChatSession");
    expect(view).not.toContain("<EmbeddedChatPane");
    expect(runtime).toContain('export type LocusRuntimeKind = "tauri" | "browser";');
    expect(runtime).not.toContain('"unity"');
    expect(runtime).not.toContain("locusUnityBridge");
    expect(runtime).not.toContain("EventSource");
    expect(runtime).not.toContain("fetch(");
    expect(runtime).not.toContain("/invoke");
    expect(app).not.toContain("isUnityHostLocation");
  });

  it("supports multiple Unity native frontend windows", () => {
    const app = read("src/App.vue");
    const viewHost = read("src/components/ViewHostWindow.vue");
    const unityService = read("src/services/unity.ts");
    const viewService = read("src/services/view.ts");
    const command = read("src-tauri/src/commands/unity_embed.rs");
    const viewCommand = read("src-tauri/src/commands/view.rs");
    const viewRuntime = read("src-tauri/src/view.rs");
    const unityBridge = read("src-tauri/src/unity_bridge/mod.rs");
    const unityWindow = read("locus_unity/Editor/LocusEditorWindow.cs");
    const bridge = read("locus_unity/Editor/LocusBridge.cs");
    const capability = read("src-tauri/capabilities/default.json");

    expect(command).toContain("pub struct UnityEmbedOpenFrontendWindowRequest");
    expect(command).toContain("pub struct UnityEmbedOpenFrontendWindowResult");
    expect(command).toContain("fn unity_embed_window_label_for_msg");
    expect(command).toContain("fn unity_embed_host_url");
    expect(command).toContain("HashMap<String, UnityEmbedAppliedState>");
    expect(command).toContain("HashMap<String, UnityEmbedTransientCloseState>");
    expect(command).toContain("unity_embed_open_frontend_window");
    expect(command).toContain("crate::unity_bridge::open_frontend_window");
    expect(unityBridge).toContain('send_message(project_path, "open_frontend_window", payload)');
    expect(bridge).toContain('case "open_frontend_window"');
    expect(unityWindow).toContain("OpenFrontendWindowFromJson");
    expect(unityWindow).toContain("CreateInstance<LocusEditorWindow>()");
    expect(unityWindow).toContain("public string windowId;");
    expect(unityWindow).toContain("public string targetKind;");
    expect(unityWindow).toContain("public string targetId;");
    expect(unityWindow).toContain("titleContent = CreateTitleContent(_windowTitle)");
    expect(app).toContain("const isUnityEmbedViewWindow");
    expect(app).toContain("<ViewHostWindow v-else embedded");
    expect(app).toContain(":initial-session-id=\"unityEmbedTargetId\"");
    expect(viewHost).toContain("embedded?: boolean");
    expect(viewHost).toContain("UNITY_EMBED_WINDOW_LABEL_PREFIX");
    expect(viewService).toContain("viewRunInUnity");
    expect(viewCommand).toContain("pub async fn view_run_in_unity");
    expect(viewRuntime).toContain("open_view_unity_embed_window");
    expect(viewRuntime).toContain('target_kind: "view".to_string()');
    expect(viewRuntime).toContain("title: Some(detail.summary.name.clone())");
    expect(viewRuntime).not.toContain('format!("Locus View - {} ({})"');
    expect(unityWindow).toContain('return string.IsNullOrEmpty(targetId) ? "View" : targetId;');
    expect(unityService).toContain("openUnityEmbeddedSessionWindow");
    expect(unityService).toContain("currentUnityEmbedWindowId");
    expect(capability).toContain('"unity-embed-*"');
  });

  it("exits the desktop app when the main window closes", () => {
    const app = read("src-tauri/src/lib.rs");
    const command = read("src-tauri/src/commands/unity_embed.rs");
    const system = read("src-tauri/src/commands/system.rs");

    expect(app).toContain("const MAIN_WINDOW_LABEL: &str = \"main\";");
    expect(app).toContain("const MAIN_WINDOW_CLOSE_REQUESTED_EVENT: &str = \"locus-main-window-close-requested\";");
    expect(app).toContain(".on_window_event(|window, event|");
    expect(app).toContain("WindowEvent::CloseRequested");
    expect(app).toContain("api.prevent_close();");
    expect(app).toContain("window.emit(MAIN_WINDOW_CLOSE_REQUESTED_EVENT, ())");
    expect(app).toContain("commands::request_app_exit");
    expect(system).toContain("pub fn request_app_exit(app_handle: AppHandle)");
    expect(system).toContain("crate::commands::destroy_unity_embed_control_window_on_main(app_handle);");
    expect(system).toContain("app_handle.exit(0);");
    expect(command).toContain("pub(crate) fn destroy_unity_embed_control_window_on_main");
    expect(command).toContain("window.destroy().or_else(|_| window.close())");
    expect(command).toContain("record_all_embed_windows_destroyed();");
    expect(command).toContain("record_window_destroyed(label);");
  });

  it("boosts Unity overlay sync while the editor window is resizing", () => {
    const unityWindow = read("locus_unity/Editor/LocusEditorWindow.cs");

    expect(unityWindow).toContain("private const double ResizeSyncIntervalSeconds = 1d / 60d;");
    expect(unityWindow).toContain("private const double ResizeBoostDurationSeconds = 0.35d;");
    expect(unityWindow).toContain("resizeBoostActive ? ResizeSyncIntervalSeconds : SyncIntervalSeconds");
    expect(unityWindow).toContain("MarkResizeSyncBoost();");
  });

  it("keeps the Unity embed WebView alive across domain reloads", () => {
    const unityWindow = read("locus_unity/Editor/LocusEditorWindow.cs");
    const command = read("src-tauri/src/commands/unity_embed.rs");

    expect(unityWindow).toContain('private const string CloseReasonDomainReload = "domainReload";');
    expect(unityWindow).toContain("AssemblyReloadEvents.beforeAssemblyReload += OnBeforeAssemblyReload;");
    expect(unityWindow).toContain("AssemblyReloadEvents.afterAssemblyReload += OnAfterAssemblyReload;");
    expect(unityWindow).toContain("EditorApplication.quitting += OnEditorQuitting;");
    expect(unityWindow).toContain('private const string CloseReasonWindowDisabled = "windowDisabled";');
    expect(unityWindow).toContain("string reason = GetDisableCloseReason();");
    expect(unityWindow).toContain("SendClose(reason);");
    expect(unityWindow).toContain("if (_assemblyReloadInProgress)");
    expect(unityWindow).toContain("return CloseReasonDomainReload;");
    expect(unityWindow).toContain("return CloseReasonWindowDisabled;");
    expect(unityWindow).toContain("public string reason;");
    expect(unityWindow).toContain("public string instanceId;");
    expect(unityWindow).toContain("public long revision;");
    expect(unityWindow).toContain("Guid.NewGuid().ToString(\"N\")");
    expect(unityWindow).toContain("private void BeginControlEpoch()");
    expect(unityWindow).toContain("_sentOpen = false;");
    expect(unityWindow).toContain("_hasLastSent = false;");
    expect(unityWindow).toContain("private static bool _creatingFrontendWindow;");
    expect(unityWindow).toContain("_frontendWindowConfigured = false;");
    expect(unityWindow).toContain("private void OnDestroy()");
    expect(unityWindow).toContain("SendClose(CloseReasonWindowClosed)");
    expect(unityWindow).toContain("instanceId = _instanceId");
    expect(unityWindow).toContain("revision = ++_controlRevision");
    expect(unityWindow).toContain("reason = reason ?? \"\"");
    expect(command).toContain('const CLOSE_REASON_DOMAIN_RELOAD: &str = "domainReload";');
    expect(command).toContain("const TRANSIENT_CLOSE_DESTROY_DELAY: Duration = Duration::from_secs(30);");
    expect(command).toContain("struct UnityEmbedTransientCloseState");
    expect(command).toContain("fn schedule_transient_close_destroy");
    expect(command).toContain("tokio::time::sleep(TRANSIENT_CLOSE_DESTROY_DELAY).await;");
    expect(command).toContain("fn is_transient_close_reason");
    expect(command).toContain("reason == CLOSE_REASON_DOMAIN_RELOAD");
    expect(command).toContain('reason == "windowDisabled"');
    expect(command).toContain("if is_transient_close_reason(&msg.reason)");
    expect(command).toContain("fn should_ignore_stale_control_message");
    expect(command).toContain("if should_ignore_stale_control_message(&label, &msg)");
    expect(command).toContain("UnityEmbedControlRevisionState");
    expect(command).toContain('msg.kind != "open"');
    expect(command).toContain("schedule_transient_close_destroy(app_handle, label);");
    expect(command).toContain("cancel_transient_close_destroy(&label);");
  });

  it("suppresses Windows mouse activation for the embedded overlay outside the composer", () => {
    const view = read("src/components/UnityEmbeddedSessionView.vue");
    const service = read("src/services/unity.ts");
    const command = read("src-tauri/src/commands/unity_embed.rs");
    const app = read("src-tauri/src/lib.rs");

    expect(view).toContain("ACTIVATION_ALLOWED_SELECTOR");
    expect(view).toContain(".chat-composer-input");
    expect(view).not.toContain("\".chat-input-shell\",");
    expect(view).not.toContain("\".chat-composer\",");
    expect(view).toContain("applyMouseActivationSuppressed(true)");
    expect(service).toContain("setUnityEmbedMouseActivationSuppressed");
    expect(service).toContain("unity_embed_set_mouse_activation_suppressed");
    expect(service).toContain("activateUnityEmbedForInput");
    expect(service).toContain("unity_embed_activate_for_input");
    expect(service).toContain("getUnityEmbedFocusDebugSnapshot");
    expect(service).toContain("unity_embed_focus_debug_snapshot");
    expect(service).toContain("mouseActivateHookInstalled");
    expect(service).toContain("mouseActivateHookedHwndCount");
    expect(service).toContain("mouseActivateBlockCount");
    expect(service).toContain("overlayChildWindow");
    expect(service).toContain("activationGuardEnabled");
    expect(command).toContain("MouseActivationState");
    expect(command).toContain("guard_enabled");
    expect(command).toContain("const USE_CHILD_EMBED_OVERLAY: bool = true;");
    expect(command).toContain("return position_popup_overlay(window, msg);");
    expect(command).toContain("transient_unity_embed_parent_owner");
    expect(command).toContain("position_transient_parent_overlay");
    expect(command).toContain("position_popup_overlay_with_owner");
    expect(command).toContain('hwnd_class(parent) != "UnityContainerWndClass"');
    expect(command).toContain('title != "Locus" && title != expected_title');
    expect(command).toContain("SetWindowLongPtrW(child, GWLP_HWNDPARENT, owner.0 as isize)");
    expect(command).toContain("let reparent_from_popup = (current_style & WS_CHILD.0) == 0;");
    expect(command).toContain("let needs_parent_update = current_parent != parent || reparent_from_popup;");
    expect(command).toContain("position_child_overlay");
    expect(command).toContain("ScreenToClient");
    expect(command).toContain("SetParent");
    expect(command).toContain("SetWindowSubclass");
    expect(command).toContain("RemoveWindowSubclass");
    expect(command).toContain("WM_MOUSEACTIVATE");
    expect(command).toContain("MA_NOACTIVATE");
    expect(command).toContain("WS_EX_NOACTIVATE");
    expect(command).toContain("set_window_visible_no_activate");
    expect(command).toContain("SW_SHOWNOACTIVATE");
    expect(command).toContain("SW_HIDE");
    expect(command).toContain("let desired_visible = should_show_window_now(&window, &msg);");
    expect(command).toContain("needs_visibility_apply(&label, desired_visible)");
    expect(command).toContain("record_applied_visibility(&label, desired_visible)");
    expect(command).toContain("collect_descendant_windows");
    expect(command).toContain("GW_CHILD");
    expect(command).toContain("mouse_hook_sync_loop");
    expect(command).toContain("activate_for_input");
    expect(command).toContain("focus_embed_window_for_input");
    expect(command).toContain("AttachThreadInput");
    expect(command).toContain("SetKeyboardFocus");
    expect(command).toContain("COREWEBVIEW2_MOVE_FOCUS_REASON_PROGRAMMATIC");
    expect(command).toContain("controller.MoveFocus");
    expect(command).toContain("for (label, window) in windows");
    expect(command).toContain("if !synced_any || !is_activation_guard_enabled()");
    expect(command).toContain("mouse_activate_hook_installed");
    expect(command).toContain("mouse_activate_hooked_hwnd_count");
    expect(command).toContain("mouse_activate_block_count");
    expect(command).toContain("activation_guard_enabled");
    expect(command).toContain("overlay_child_window");
    expect(command).toContain("unity_embed_set_mouse_activation_suppressed");
    expect(command).toContain("unity_embed_activate_for_input");
    expect(command).toContain("UnityEmbedFocusDebugSnapshot");
    expect(command).toContain("foreground_title");
    expect(app).toContain("commands::unity_embed_set_mouse_activation_suppressed");
    expect(app).toContain("commands::unity_embed_activate_for_input");
    expect(app).toContain("commands::unity_embed_focus_debug_snapshot");
  });

  it("sends the current Unity host HWND for child-window mounting", () => {
    const unityWindow = read("locus_unity/Editor/LocusEditorWindow.cs");

    expect(unityWindow).toContain("GetUnityHostHwnd(_screenX, _screenY, _screenWidth, _screenHeight)");
    expect(unityWindow).toContain("FindUnityHostWindowForRect");
    expect(unityWindow).toContain("EnumWindows");
    expect(unityWindow).toContain("GetWindowThreadProcessId");
    expect(unityWindow).toContain("IntersectionArea");
  });

  it("bridges Unity asset drops into the embedded composer attachment bar", () => {
    const unityWindow = read("locus_unity/Editor/LocusEditorWindow.cs");
    const app = read("src-tauri/src/lib.rs");
    const vueApp = read("src/App.vue");
    const tauriConfig = read("src-tauri/tauri.conf.json");
    const command = read("src-tauri/src/commands/unity_embed.rs");
    const workspaceCommands = read("src-tauri/src/commands/workspace.rs");
    const service = read("src/services/unity.ts");
    const view = read("src/components/UnityEmbeddedSessionView.vue");
    const dropTarget = read("src/composables/useUnityAssetDropTarget.ts");
    const input = read("src/components/chat/RichChatInput.vue");
    const transcript = read("src/components/chat/ChatTranscript.vue");
    const bridge = read("locus_unity/Editor/LocusBridge.cs");
    const consoleBridge = read("locus_unity/Editor/LocusBridge.Console.cs");
    const registry = read("src/composables/useCommandRegistry.ts");

    expect(app).toContain(".on_webview_event(|webview, event|");
    expect(app).toContain("commands::handle_unity_embed_webview_event(webview, event);");
    expect(app).toContain("commands::handle_locus_window_event(window, event);");
    expect(app).toContain("commands::unity_embed_commit_asset_drop");
    expect(vueApp).toContain("useUnityAssetDropTarget({");
    expect(vueApp).toContain('enabled: () => !isStandaloneWindow');
    expect(vueApp).toContain('@dragover.capture="handleMainUnityAssetDrag"');
    expect(vueApp).toContain('@drop.capture="handleMainUnityAssetDrop"');
    expect(tauriConfig).toContain('"dragDropEnabled": true');
    expect(command).toContain("pub(crate) fn handle_unity_embed_webview_event");
    expect(command).toContain("pub(crate) fn handle_locus_window_event");
    expect(command).toContain("tauri::WindowEvent::DragDrop");
    expect(command).toContain("handle_locus_drop_paths");
    expect(command).toContain("tauri::DragDropEvent::Drop { paths, .. }");
    expect(command).toContain("commit_cached_unity_asset_drag_drop_to(webview.app_handle(), webview.label())");
    expect(command).toContain("commit_cached_unity_asset_drag_drop_to(window.app_handle(), window.label())");
    expect(command).toContain("fn commit_cached_unity_asset_drag_drop_to");
    expect(command).toContain("unity_file_drop_asset_refs(&workspace_path, &paths)");
    expect(command).toContain("locus_file_drop_refs(&workspace_path, &paths)");
    expect(command).toContain('"locus-file-drop"');
    expect(command).toContain("fn is_locus_view_window_label");
    expect(command).toContain("fn locus_view_window_labels");
    expect(command).toContain("fn locus_frontend_drop_window_labels");
    expect(command).toContain("is_locus_view_window_label(label)");
    expect(command).toContain("fn unity_relative_drop_path");
    expect(command).toContain("fn cache_unity_embed_asset_drag_refs");
    expect(command).toContain("pub async fn unity_embed_commit_asset_drop");
    expect(command).toContain('kind: "asset".to_string()');
    expect(command).toContain('source: Some("unity".to_string())');
    expect(command).toContain('"unity-embed-asset-drop"');
    expect(command).toContain("UnityEmbedAssetDragStatePayload");
    expect(command).toContain('"unity-embed-asset-drag-state"');
    expect(command).toContain("ensure_unity_embed_asset_drag_release_monitor(app_handle)");
    expect(command).toContain("monitor_unity_embed_asset_drag_release");
    expect(command).toContain("unity_asset_drag_release_probe");
    expect(command).toContain("UnityAssetDragReleaseTarget::MainWindow");
    expect(command).toContain("UnityAssetDragReleaseTarget::ViewWindow");
    expect(command).toContain("if !saw_left_button_down");
    expect(command).toContain("emit_locus_asset_drop_to(&app_handle, MAIN_WINDOW_LABEL, refs)");
    expect(command).toContain("emit_locus_asset_drop_to(&app_handle, &label, refs)");
    expect(command).toContain("WindowFromPoint");
    expect(command).toContain("GetAsyncKeyState");
    expect(command).toContain(".disable_drag_drop_handler()");
    expect(unityWindow).toContain("public DroppedAssetRef[] assetRefs;");
    expect(unityWindow).toContain('[MenuItem("Assets/Send to Locus", false, 0)');
    expect(unityWindow).toContain('[MenuItem("GameObject/Send to Locus", false, 0)');
    expect(unityWindow).not.toContain("InitializeConsoleIntegration");
    expect(unityWindow).not.toContain("locus-console-send-button");
    expect(unityWindow).not.toContain('text = "Send to Locus"');
    expect(unityWindow).not.toContain("HandleConsoleSendButtonMouseDown");
    expect(unityWindow).not.toContain("SendConsoleToLocus");
    expect(bridge).toContain('case "get_console_text"');
    expect(bridge).toContain("BuildConsoleTextPayloadJson()");
    expect(consoleBridge).toContain("BuildConsoleTextPayloadJson");
    expect(consoleBridge).toContain("TryBuildConsoleTextEntriesFromLogEntries");
    expect(consoleBridge).toContain("AddConsoleEntry");
    expect(consoleBridge).toContain("ConvertMemberToInt");
    expect(consoleBridge).toContain("const int ScriptingWarning");
    expect(consoleBridge).toContain("const int VisualScriptingError");
    expect(consoleBridge).not.toContain('return "Assert";');
    expect(workspaceCommands).toContain("pub async fn get_unity_console_text");
    expect(workspaceCommands).toContain('send_message(&cwd, "get_console_text", "")');
    expect(app).toContain("commands::get_unity_console_text");
    expect(unityWindow).toContain("BuildSelectedAssetRefs");
    expect(unityWindow).toContain("SendSelectedRefsToLocus");
    expect(unityWindow).toContain("WritePipeLineOnce");
    expect(unityWindow).toContain("HandleUnityObjectDrag();");
    expect(unityWindow).toContain("SendAssetDragState(false);");
    expect(unityWindow).toContain("SendAssetDragStateMessage(assetRefs);");
    expect(unityWindow).toContain("internal static void PublishCurrentUnityAssetDragState(bool force)");
    expect(unityWindow).toContain("SendAssetDragStateMessageOnce(assetRefs)");
    expect(unityWindow).toContain('type = "assetDrag"');
    expect(unityWindow).toContain("BuildAssetRefsSignature");
    expect(unityWindow).toContain("DragAndDrop.objectReferences");
    expect(unityWindow).toContain("DragAndDrop.paths");
    expect(unityWindow).toContain('type = "assetDrop"');
    expect(unityWindow).toContain('kind = "sceneObject"');
    expect(unityWindow).toContain('source = "unity"');
    expect(unityWindow).toContain('message.type == "open" || message.type == "update"');
    expect(command).toContain("asset_refs: Option<Vec<UnityEmbedAssetRef>>");
    expect(command).toContain('"assetDrop" =>');
    expect(command).toContain('"assetDrag" =>');
    expect(command).toContain('"consoleText" =>');
    expect(command).toContain("text_entries: Option<Vec<UnityEmbedTextDropEntry>>");
    expect(command).toContain("entries: Vec<UnityEmbedTextDropEntry>");
    expect(command).toContain('"unity-embed-text-drop"');
    expect(service).toContain("commitUnityEmbedAssetDrop");
    expect(service).toContain("unity_embed_commit_asset_drop");
    expect(service).toContain("getUnityConsoleText");
    expect(service).toContain("get_unity_console_text");
    expect(service).toContain("subscribeUnityEmbedAssetDrop");
    expect(service).toContain("subscribeUnityEmbedTextDrop");
    expect(service).toContain("subscribeLocusFileDrop");
    expect(service).toContain("subscribeUnityEmbedAssetDragState");
    expect(registry).toContain('name: "/unity-console"');
    expect(registry).toContain('commandType: "unity-console"');
    expect(service).not.toContain("[Locus][UnityEmbedDrag]");
    expect(view).toContain("@dragover.capture=\"handleUnityAssetDrag\"");
    expect(view).toContain("@drop.capture=\"handleUnityAssetDrop\"");
    expect(view).toContain("useUnityAssetDropTarget()");
    expect(dropTarget).toContain("commitUnityEmbedAssetDrop()");
    expect(dropTarget).toContain("subscribeUnityEmbedAssetDragState(handleUnityAssetDragState)");
    expect(dropTarget).toContain("hasUnityAssetDragState()");
    expect(dropTarget).toContain("if (!isUnityExternalFileDrag(event) && !hasUnityAssetDragState()) return false;");
    expect(dropTarget).toContain("UNITY_ASSET_DRAG_STATE_TTL_MS");
    expect(view).not.toContain("handleDragDebug");
    expect(input).toContain("assetRefAttachments = ref<AssetRefAttachment[]>([])");
    expect(input).toContain("consoleTextAttachments = ref<ConsoleTextAttachment[]>([])");
    expect(input).toContain("localFileAttachments = ref<LocalFileAttachment[]>([])");
    expect(input).toContain("subscribeUnityEmbedAssetDrop((payload)");
    expect(input).toContain("subscribeUnityEmbedTextDrop((payload)");
    expect(input).toContain("subscribeLocusFileDrop((payload)");
    expect(input).toContain("checkUnityConnectionStatus");
    expect(input).toContain("getUnityConsoleText");
    expect(input).toContain("attachUnityConsoleFromCommand");
    expect(input).toContain("function addConsoleTextAttachment(");
    expect(input).toContain("function addLocalFileAttachments(");
    expect(input).toContain("shouldGroupLocalFiles");
    expect(input).toContain("singleLocalFileAttachment");
    expect(input).toContain("addConsoleTextAttachment(payload)");
    expect(input).toContain("addLocalFileAttachments(payload.files ?? [])");
    expect(input).toContain("entries?: UnityEmbedTextDropEntry[] | null;");
    expect(input).toContain("<locus-console>");
    expect(input).toContain("<locus-local-files>");
    expect(input).toContain("Read contents only when needed");
    expect(input).toContain("appendConsoleTextPromptBlock");
    expect(input).toContain("appendConsoleTextDisplayBlock");
    expect(input).toContain("appendLocalFilesPromptBlock");
    expect(input).toContain("function consoleTextLevelClass(level: string)");
    expect(input).toContain(":class=\"consoleTextLevelClass(item.level)\"");
    expect(input).toContain('class="composer-attachment-list"');
    expect(input).toContain("flex-wrap: nowrap;");
    expect(input).toContain('class="console-text-group"');
    expect(input).toContain('class="console-text-details-popover"');
    expect(input).toContain('class="local-file-group"');
    expect(input).toContain('class="local-file-chip"');
    expect(input).toContain('class="local-file-details-popover"');
    expect(input).not.toContain("consoleTextPreview");
    expect(input).toContain("ASSET_REF_COLLAPSE_THRESHOLD = 5");
    expect(input).toContain("shouldCollapseAssetRefs");
    expect(input).toContain('class="asset-ref-group"');
    expect(input).toContain('class="asset-ref-details-popover"');
    expect(input).toContain("<locus-references>");
    expect(transcript).toContain("messageAssetRefs(item.message)");
    expect(transcript).toContain('class="chat-transcript-user-asset-refs"');
    expect(transcript).toContain("userMessageConsoleEntries(message.content)");
    expect(transcript).toContain('class="chat-transcript-user-console"');
    expect(transcript).toContain("chat.consoleRefs.defaultTitle");
    expect(transcript).toContain("chat.consoleRefs.charCount");
  });

  it("routes embedded Ctrl-click asset refs to a locked Unity Inspector", () => {
    const chat = read("src/components/ChatView.vue");
    const service = read("src/services/unity.ts");
    const commands = read("src-tauri/src/commands/workspace.rs");
    const bridge = read("src-tauri/src/unity_bridge/mod.rs");
    const unityBridge = read("locus_unity/Editor/LocusBridge.cs");
    const unityTypes = read("locus_unity/Editor/LocusBridge.Types.cs");
    const app = read("src-tauri/src/lib.rs");

    expect(chat).toContain("function isUnityEmbeddedWindow()");
    expect(chat).toContain('window.location.pathname === "/unity-embed"');
    expect(chat).toContain("e.ctrlKey || e.metaKey");
    expect(chat).toContain("openUnityAssetInspector(filePath)");
    expect(service).toContain("open_unity_asset_inspector");
    expect(commands).toContain("pub async fn open_unity_asset_inspector");
    expect(bridge).toContain('send_message(project_path, "open_asset_inspector"');
    expect(app).toContain("commands::open_unity_asset_inspector");
    expect(unityBridge).toContain('case "open_asset_inspector"');
    expect(unityTypes).toContain("internal static class LocusAssetInspectorUtility");
    expect(unityTypes).toContain("TryOpenPropertyEditor");
    expect(unityTypes).toContain("LocusLockedAssetInspectorWindow");
    expect(unityTypes).not.toContain("Selection.activeObject = obj");
  });

  it("offers reference context-menu actions for assets and knowledge documents", () => {
    const chat = read("src/components/ChatView.vue");
    const transcript = read("src/components/chat/ChatTranscript.vue");
    const assetChip = read("src/components/AssetChip.vue");
    const zh = read("src/language/zh.json");
    const en = read("src/language/en.json");

    expect(transcript).toContain('(e: "contentContextmenu", event: MouseEvent): void;');
    expect(transcript).toContain("@contextmenu=\"emitContentContextmenu\"");
    expect(transcript).toContain('context-menu-mode="inherit"');
    expect(chat).toContain("@content-contextmenu=\"handleContentContextMenu\"");
    expect(chat).toContain("function handleContentContextMenu(e: MouseEvent)");
    expect(chat).toContain("function assetContextTargetFromElement(target: Element)");
    expect(chat).toContain("function parseKnowledgeDocumentRefPath(filePath: string)");
    expect(chat).toContain(".md-knowledge-ref[data-knowledge-path]");
    expect(chat).toContain("KNOWLEDGE_DOCUMENT_FILE_RE");
    expect(chat).toContain('kind: "file"');
    expect(chat).toContain("assetRefContextCanOpenInEditor");
    expect(chat).toContain("assetRefContextSupportsUnity");
    expect(chat).toContain(".md-workspace-ref[data-workspace-path]");
    expect(chat).toContain('class="asset-ref-ctx-menu"');
    expect(chat).toContain("doAssetRefOpenInEditor");
    expect(chat).toContain("doAssetRefShowInFolder");
    expect(chat).toContain("doAssetRefCopyPath");
    expect(chat).toContain("doAssetRefSelectInUnity");
    expect(chat).toContain("doAssetRefOpenInKnowledge");
    expect(chat).toContain("function handleKnowledgeRefClick");
    expect(chat).toContain("knowledgeRevealTarget({");
    expect(chat).toContain("uiStore.stageKnowledgeSelection({");
    expect(chat).toContain("openFileExternal(target.filePath)");
    expect(chat).toContain("showInFolder(target.filePath)");
    expect(chat).toContain("navigator.clipboard.writeText(path)");
    expect(chat).toContain("selectUnityAsset(target.assetPath)");
    expect(chat).toContain('t("common.openInFileExplorer")');
    expect(chat).toContain('t("common.openInKnowledge")');
    expect(chat).toContain('t("common.copyPath")');
    expect(assetChip).toContain(':data-ref-kind="effectiveKind"');
    expect(assetChip).toContain(":data-knowledge-type=\"knowledgeRef?.docType\"");
    expect(assetChip).toContain(":data-knowledge-path=\"knowledgeRef?.path\"");
    expect(assetChip).toContain("uiStore.setTab(\"knowledge\")");
    expect(assetChip).toContain(':data-asset-path="effectiveKind === \'asset\' ? normalizedPath : undefined"');
    expect(assetChip).toContain(":data-scene-path=\"sceneObjectRef?.scenePath\"");
    expect(assetChip).toContain('contextMenuMode?: "copyPath" | "inherit";');
    expect(assetChip).toContain('@contextmenu="handleContextMenu"');
    expect(assetChip).toContain("async function handleContextMenu(event: MouseEvent)");
    expect(assetChip).toContain("navigator.clipboard.writeText(path)");
    expect(assetChip).toContain('operation: "assetChipCopyPath"');
    expect(zh).toContain('"common.openInFileExplorer": "在文件资源管理器中打开"');
    expect(zh).toContain('"common.openInKnowledge": "在知识页中打开"');
    expect(zh).toContain('"common.copyPath": "复制路径"');
    expect(en).toContain('"common.openInFileExplorer": "Open in File Explorer"');
    expect(en).toContain('"common.openInKnowledge": "Open in Knowledge"');
    expect(en).toContain('"common.copyPath": "Copy Path"');
  });

  it("routes scene object refs to Unity selection and locked inspectors", () => {
    const markdownInject = read("src/composables/markdownInject.ts");
    const chat = read("src/components/ChatView.vue");
    const assetChip = read("src/components/AssetChip.vue");
    const service = read("src/services/unity.ts");
    const commands = read("src-tauri/src/commands/workspace.rs");
    const bridge = read("src-tauri/src/unity_bridge/mod.rs");
    const unityBridge = read("locus_unity/Editor/LocusBridge.cs");
    const unityTypes = read("locus_unity/Editor/LocusBridge.Types.cs");
    const app = read("src-tauri/src/lib.rs");

    expect(markdownInject).toContain("md-unity-scene-object-ref");
    expect(markdownInject).toContain("data-scene-path");
    expect(markdownInject).toContain("data-scene-object-path");
    expect(chat).toContain("selectUnitySceneObject");
    expect(chat).toContain("openUnitySceneObjectInspector");
    expect(chat).toContain("function shouldOpenUnitySceneObjectInspector");
    expect(chat).toContain("notifyUnitySceneObjectError");
    expect(chat).toContain('notificationStore.addNotice("warning"');
    expect(assetChip).toContain("notifyUnitySceneObjectError");
    expect(service).toContain("select_unity_scene_object");
    expect(service).toContain("open_unity_scene_object_inspector");
    expect(service).toContain("classifyUnitySceneObjectError");
    expect(commands).toContain("pub async fn select_unity_scene_object");
    expect(commands).toContain("pub async fn open_unity_scene_object_inspector");
    expect(bridge).toContain('send_message(project_path, "select_scene_object"');
    expect(bridge).toContain('send_message(project_path, "open_scene_object_inspector"');
    expect(app).toContain("commands::select_unity_scene_object");
    expect(app).toContain("commands::open_unity_scene_object_inspector");
    expect(unityBridge).toContain('case "select_scene_object"');
    expect(unityBridge).toContain('case "open_scene_object_inspector"');
    expect(unityTypes).toContain("internal static class LocusSceneObjectUtility");
    expect(unityTypes).toContain("Selection.activeGameObject = target");
    expect(unityTypes).toContain("OpenLockedObjectInspector(target)");
  });

  it("queues Locus refs for Unity native IMGUI drag start", () => {
    const markdownInject = read("src/composables/markdownInject.ts");
    const markdownRenderer = read("src/components/MarkdownRenderer.vue");
    const assetChip = read("src/components/AssetChip.vue");
    const dragSource = read("src/composables/useUnityReferenceDragSource.ts");
    const service = read("src/services/unity.ts");
    const command = read("src-tauri/src/commands/unity_embed.rs");
    const bridge = read("src-tauri/src/unity_bridge/mod.rs");
    const app = read("src-tauri/src/lib.rs");
    const unityBridge = read("locus_unity/Editor/LocusBridge.cs");
    const editorWindow = read("locus_unity/Editor/LocusEditorWindow.cs");
    const unityTypes = read("locus_unity/Editor/LocusBridge.Types.cs");

    expect(markdownInject).toContain('draggable="true"');
    expect(markdownRenderer).toContain("function handleMarkdownDragStart(event: DragEvent)");
    expect(markdownRenderer).toContain("function handleMarkdownPointerDown(event: PointerEvent)");
    expect(markdownRenderer).toContain("function localFileFromMarkdownDragTarget(target: Element)");
    expect(markdownRenderer).toContain("startUnityReferenceHtmlDrag(event, [ref])");
    expect(markdownRenderer).toContain("armUnityReferencePointerDrag(event, [ref])");
    expect(markdownRenderer).toContain("startLocusFileHtmlDrag(event, [file])");
    expect(markdownRenderer).toContain("armLocusFilePointerDrag(event, [file])");
    expect(assetChip).toContain(':draggable="!!unityDragRef"');
    expect(assetChip).toContain('@pointerdown="handlePointerDown"');
    expect(assetChip).toContain('@dragstart="handleDragStart"');
    expect(assetChip).toContain('@pointerdown.stop.prevent');
    expect(assetChip).toContain('@dragstart.stop.prevent');
    expect(dragSource).toContain("POINTER_DRAG_THRESHOLD_PX");
    expect(dragSource).toContain("NATIVE_FILE_DRAG_RESTORE_MS");
    expect(dragSource).toContain("UNITY_ASSET_REF_ROOT_RE");
    expect(dragSource).toContain('window.location.pathname === "/unity-embed"');
    expect(dragSource).toContain("event.preventDefault()");
    expect(dragSource).toContain("shouldStartNativeAssetFileDrag(refs)");
    expect(dragSource).toContain("shouldWarmupUnityDrag(refs)");
    expect(dragSource).toContain("isUnityAssetRefPath(ref.path)");
    expect(dragSource).toContain("suppressHtmlDraggable(event)");
    expect(dragSource).toContain("startUnityNativeAssetFileDrag(refs)");
    expect(dragSource).toContain("startLocusNativeFileDrag(files)");
    expect(dragSource).toContain("setUnityEmbedDragPassthrough(true)");
    expect(dragSource).toContain("startUnityEmbedAssetDrag(refs)");
    expect(dragSource).toContain("startUnityAssetDragWarmup(refs)");
    expect(dragSource).toContain("cancelUnityAssetDragWarmup(warmup)");
    expect(dragSource).toContain("beginNativeAssetFileDrag(refs, warmup)");
    expect(dragSource).toContain("beginUnityReferencePointerDrag(refs, warmup)");
    expect(dragSource).toContain("Promise.allSettled([armPromise, nativeDragPromise])");
    expect(dragSource).toContain("Promise.all([armPromise, passthroughPromise])");
    expect(service).toContain("unity_embed_set_drag_passthrough");
    expect(service).toContain("unity_embed_start_asset_drag");
    expect(service).toContain("unity_embed_cancel_asset_drag");
    expect(service).toContain("unity_embed_start_native_asset_file_drag");
    expect(service).toContain("locus_start_native_file_drag");
    expect(command).toContain("pub async fn unity_embed_set_drag_passthrough");
    expect(command).toContain("pub async fn unity_embed_start_asset_drag");
    expect(command).toContain("pub async fn unity_embed_cancel_asset_drag");
    expect(command).toContain("pub async fn unity_embed_start_native_asset_file_drag");
    expect(command).toContain("pub async fn locus_start_native_file_drag");
    expect(command).toContain("native_locus_file_drag_paths");
    expect(command).toContain("run_on_main_thread");
    expect(command).toContain("native_asset_file_drag_paths");
    expect(command).toContain("unity_ref_drag_preview_label");
    expect(command).toContain("start_reference_drag_preview");
    expect(command).toContain("IDragSourceHelper");
    expect(command).toContain("SHDRAGIMAGE");
    expect(command).toContain("InitializeFromBitmap");
    expect(command).toContain("CF_HDROP");
    expect(command).toContain("DROPFILES");
    expect(command).toContain("DoDragDrop");
    expect(command).toContain("sanitize_locus_outbound_drag_refs");
    expect(command).toContain("WS_EX_TRANSPARENT");
    expect(command).toContain("ReleaseCapture");
    expect(command).toContain("set_drag_passthrough");
    expect(bridge).toContain('send_message(project_path, "start_asset_drag"');
    expect(app).toContain("commands::unity_embed_set_drag_passthrough");
    expect(app).toContain("commands::unity_embed_start_asset_drag");
    expect(app).toContain("commands::unity_embed_cancel_asset_drag");
    expect(app).toContain("commands::unity_embed_start_native_asset_file_drag");
    expect(app).toContain("commands::locus_start_native_file_drag");
    expect(unityBridge).toContain('case "start_asset_drag"');
    expect(unityBridge).toContain("QueueOutboundAssetDrag(request.refs, out status)");
    expect(editorWindow).toContain("internal static bool QueueOutboundAssetDrag");
    const externalDragBridge = read("locus_unity/Editor/LocusExternalAssetDragBridge.cs");
    const queueMethod = editorWindow.slice(
      editorWindow.indexOf("internal static bool QueueOutboundAssetDrag"),
      editorWindow.indexOf('[MenuItem("Assets/Send to Locus"', editorWindow.indexOf("internal static bool QueueOutboundAssetDrag")),
    );
    expect(queueMethod).toContain("LocusExternalAssetDragBridge.QueueAssetDrag(sanitized, out message)");
    expect(queueMethod).not.toContain("GetWindow<LocusEditorWindow>()");
    expect(queueMethod).not.toContain("window.Show()");
    expect(externalDragBridge).toContain('typeof(GUIUtility).GetField("beforeEventProcessed"');
    expect(externalDragBridge).toContain("InstallBeforeEventProcessedHandler();");
    expect(externalDragBridge).toContain("EditorApplication.update += GlobalUpdateHandler;");
    expect(externalDragBridge).toContain("HandleBeforeEventProcessed(EventType eventType, KeyCode keyCode)");
    expect(externalDragBridge).toContain("HandleGlobalUpdate()");
    expect(externalDragBridge).toContain("ShouldPublishAssetDragStateOnGlobalUpdate()");
    expect(externalDragBridge).toContain("LocusEditorWindow.HasCurrentUnityDragAndDropRefs()");
    expect(externalDragBridge).toContain("LocusEditorWindow.PublishCurrentUnityAssetDragState(false)");
    expect(externalDragBridge).toContain("LocusEditorWindow.PublishCurrentUnityAssetDragState(eventType == EventType.DragPerform)");
    expect(editorWindow).toContain("DroppedAssetRefsScratch");
    expect(editorWindow).toContain("HashSet<DroppedAssetRefKey>");
    expect(externalDragBridge).toContain("internal static bool QueueAssetDrag");
    expect(externalDragBridge).toContain("EventType.MouseDrag");
    expect(externalDragBridge).toContain("StartQueuedDrag()");
    expect(externalDragBridge).toContain("ApplyArmedDragPayload()");
    expect(externalDragBridge).toContain("PostPerformRepaintFrames");
    expect(externalDragBridge).toContain("RepaintAfterDragPerformIfNeeded");
    expect(externalDragBridge).toContain("RepaintDropTargetWindowsAfterDragPerform");
    expect(externalDragBridge).toContain("SceneView.RepaintAll();");
    expect(externalDragBridge).toContain("EditorApplication.RepaintHierarchyWindow();");
    expect(externalDragBridge).toContain("DropTargetWindowKind");
    expect(externalDragBridge).toContain("RepaintAfterInstanceDetectedIfNeeded");
    expect(externalDragBridge).toContain("IsSceneInstanceObject");
    expect(externalDragBridge).toContain("SnapshotObjectArray");
    expect(externalDragBridge).toContain("DragAndDrop.PrepareStartDrag();");
    expect(externalDragBridge).toContain("DragAndDrop.StartDrag(title)");
    expect(externalDragBridge).toContain("DragAndDrop.objectReferences = references;");
    expect(externalDragBridge).toContain("TrySplitSceneObjectRefPath");
    expect(externalDragBridge).toContain("LocusSceneObjectUtility.ResolveSceneObject(scenePath, objectPath)");
    expect(unityTypes).toContain("public static GameObject ResolveSceneObject");
  });
});
