import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";

const cwd = process.cwd();

function read(relPath: string) {
  return readFileSync(resolve(cwd, relPath), "utf8");
}

describe("View host tabs", () => {
  it("renders draggable View tabs and registers merged tab hosts", () => {
    const host = read("src/components/ViewHostWindow.vue");
    const service = read("src/services/view.ts");
    const unityService = read("src/services/unity.ts");
    const commands = read("src-tauri/src/commands/view.rs");
    const unityCommands = read("src-tauri/src/commands/unity_embed.rs");
    const runtime = read("src-tauri/src/view.rs");
    const app = read("src-tauri/src/lib.rs");
    const appView = read("src/App.vue");
    const capabilities = read("src-tauri/capabilities/default.json");

    expect(host).toContain('const VIEW_HOST_TABS_MERGE_EVENT = "view-host-tabs-merge"');
    expect(host).toContain('const VIEW_HOST_TABS_MERGE_DONE_EVENT = "view-host-tabs-merge-done"');
    expect(host).toContain('const VIEW_HOST_TABS_SELECT_EVENT = "view-host-tabs-select"');
    expect(host).toContain('const VIEW_HOST_TABS_DROP_TARGET_EVENT = "view-host-tabs-drop-target"');
    expect(host).toContain('role="tablist"');
    expect(host).toContain('class="view-host-tabs"');
    expect(host).toContain("data-tauri-drag-region");
    expect(host).toContain('class="view-host-tab"');
    expect(host).toContain('@pointerdown="startTabDrag($event, tab.id)"');
    expect(host).toContain('@click="onTabClick($event, tab.id)"');
    expect(host).toContain(".view-host-tabs {\n  -webkit-app-region: drag;");
    expect(host).toContain(".view-host-tab {\n  -webkit-app-region: no-drag;");
    expect(host).toContain("background: color-mix(in srgb, var(--panel-bg) 64%, var(--sidebar-bg) 36%)");
    expect(host).toContain("box-shadow: inset 0 2px 0 var(--accent-color)");
    expect(host).toContain("cursor: grab");
    expect(host).toContain("TauriWindow.getAll()");
    expect(host).toContain("findTabDropTargetAt");
    expect(host).toContain("emitTabDropTargetState");
    expect(host).toContain("startLocusDragPreview");
    expect(host).toContain("stopLocusDragPreview");
    expect(host).toContain("startTabDragPreview(state.tabId)");
    expect(host).toContain("is-external-tab-drop-target");
    expect(host).toContain(".view-host-tab.dragging");
    expect(host).toContain("targetLabel?: string");
    expect(host).toContain("allowPoolClaim?: boolean");
    expect(host).toContain('viewHostContentLog("claim-ignored-target"');
    expect(host).toContain("payload.allowPoolClaim === true");
    expect(host).toContain("if (!hasHostedTab && !canClaimPoolTab)");
    expect(host).toContain('prepareViewHostPool("host-mounted")');
    expect(host).toContain('prepareViewHostPool("host-ready")');
    expect(host).toContain('viewHostContentLog("pool-ready-done"');
    expect(host).toContain("mergeTabIntoWindow");
    expect(host).toContain("createTabMergeDoneWaiter");
    expect(host).toContain("keepExistingForHost: true");
    expect(host).toContain("isCurrentTabBandAt");
    expect(host).toContain("detachTab");
    expect(host).toContain("viewDetachTab({");
    expect(host).not.toContain("appWindow.setPosition");
    expect(host).toContain("viewSetTabHost({ hostLabel: currentWindowLabel, viewIds })");
    expect(host).toContain("interface ViewRuntimeRecord");
    expect(host).toContain("visibleRuntimeRecords");
    expect(host).toContain('v-show="record.viewId === activeViewId && record.component"');
    expect(host).toContain("usePersistentViewContentPool");
    expect(host).toContain("viewContentMount(mountRequest)");
    expect(host).toContain("viewContentHide(viewId)");
    expect(host).toContain('const VIEW_CONTENT_WINDOW_LABEL_PREFIX = "view-content-"');
    expect(host).toContain("geometrySyncQueued");
    expect(host).toContain("removeTab(tab.id, { releaseContent: false })");

    expect(service).toContain("export interface ViewSetTabHostRequest");
    expect(service).toContain("keepExistingForHost?: boolean");
    expect(service).toContain("export interface ViewDetachTabRequest");
    expect(service).toContain("export interface ViewContentMountRequest");
    expect(service).toContain("isViewHostPoolWindowLocation");
    expect(service).toContain('export const VIEW_CONTENT_PATH = "/view-content"');
    expect(service).toContain('ipcInvoke<void>("view_set_tab_host"');
    expect(service).toContain('ipcInvoke<ViewRunResult>("view_detach_tab"');
    expect(service).toContain('ipcInvoke<ViewRunResult>("view_host_pool_prepare"');
    expect(service).toContain('ipcInvoke<void>("view_host_pool_ready"');
    expect(service).toContain('ipcInvoke<ViewRunResult>("view_content_mount"');
    expect(service).toContain('ipcInvoke<void>("view_content_hide"');
    expect(unityService).toContain('runtime.invoke("locus_start_drag_preview"');
    expect(unityService).toContain('runtime.invoke("locus_stop_drag_preview"');
    expect(commands).toContain("pub async fn view_set_tab_host");
    expect(commands).toContain("pub async fn view_detach_tab");
    expect(commands).toContain("pub async fn view_host_pool_prepare");
    expect(commands).toContain("pub async fn view_host_pool_ready");
    expect(commands).toContain("pub async fn view_content_mount");
    expect(commands).toContain("pub async fn view_content_hide");
    expect(unityCommands).toContain("pub async fn locus_start_drag_preview");
    expect(unityCommands).toContain("pub async fn locus_stop_drag_preview");
    expect(unityCommands).toContain("VIEW_CONTENT_WINDOW_LABEL_PREFIX");
    expect(unityCommands).toContain("locus_view_content_window_labels");
    expect(app).toContain("commands::locus_start_drag_preview");
    expect(app).toContain("commands::locus_stop_drag_preview");
    expect(app).toContain("commands::view_host_pool_prepare");
    expect(app).toContain("commands::view_host_pool_ready");
    expect(app).toContain("commands::view_content_mount");
    expect(appView).toContain("isViewContentWindowLocation");
    expect(appView).toContain('<ViewHostWindow v-else-if="isViewContentWindow" embedded />');
    expect(runtime).toContain("fn view_tab_hosts()");
    expect(runtime).toContain("set_view_tab_host_sync");
    expect(runtime).toContain("emit_to(");
    expect(runtime).toContain('"targetLabel": window_label');
    expect(runtime).toContain('"allowPoolClaim": allow_pool_claim');
    expect(runtime).toContain("keep_existing_for_host");
    expect(runtime).toContain("ensure_view_host_pool_window");
    expect(runtime).toContain("mark_view_host_pool_ready");
    expect(runtime).toContain("VIEW_HOST_POOL_ROUTE");
    expect(runtime).toContain("Some((-32000.0, -32000.0))");
    expect(runtime).toContain("detach_view_tab_window");
    expect(runtime).toContain("mount_view_content_window");
    expect(runtime).toContain("VIEW_CONTENT_DESTROY_DELAY");
    expect(runtime).toContain("view_content_window_label");
    expect(runtime).toContain("detached_view_window_label");
    expect(runtime).toContain("active_view_window_label(app_handle, view_id)");
    expect(runtime).toContain("active_view_content_window_label(app_handle, view_id)");
    expect(runtime).toContain("let content_label = view_content_window_label(view_id)");
    expect(runtime).toContain("get_webview_window(&content_label)");
    expect(capabilities).not.toContain('"core:window:allow-set-position"');
    expect(capabilities).toContain('"core:window:allow-get-all-windows"');
    expect(capabilities).toContain('"core:window:allow-cursor-position"');
  });
});
